# Generated by Django 5.0.3 on 2024-03-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True)),
                ('room_type', models.CharField(choices=[('Regular', 'Regular'), ('ICU', 'Intensive Care Unit'), ('OR', 'Operating Room')], default='Regular', max_length=20)),
                ('capacity', models.PositiveIntegerField(default=1)),
                ('floor', models.PositiveSmallIntegerField(blank=True, default=1)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('available', models.BooleanField(default=True)),
                ('availability_start_date', models.DateField(blank=True, null=True)),
                ('availability_end_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
