# Generated by Django 5.0.3 on 2024-04-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_mgmt', '0002_roomtype_remove_room_room_type_alter_room_floor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_types',
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('Regular', 'Regular'), ('ICU', 'Intensive Care Unit'), ('OR', 'Operating Room')], default='Regular', max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.PositiveSmallIntegerField(blank=True, default=1),
        ),
        migrations.DeleteModel(
            name='RoomType',
        ),
    ]
