# Generated by Django 5.0.3 on 2024-03-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar.jpg', null=True, upload_to='profile_avatars'),
        ),
    ]
