# Generated by Django 5.0.3 on 2024-03-18 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('CARDIOLOGY', 'Cardiology'), ('PEDIATRICS', 'Pediatrics'), ('SURGERY', 'Surgery'), ('NEUROLOGY', 'Neurology'), ('ORTHOPEDICS', 'Orthopedics'), ('ONCOLOGY', 'Oncology'), ('DERMATOLOGY', 'Dermatology'), ('GASTROENTEROLOGY', 'Gastroenterology'), ('UROLOGY', 'Urology'), ('GYNECOLOGY', 'Gynecology'), ('OPHTHALMOLOGY', 'Ophthalmology'), ('OTOLARYNGOLOGY', 'Otolaryngology'), ('RADIOLOGY', 'Radiology'), ('PATHOLOGY', 'Pathology'), ('EMERGENCY_MEDICINE', 'Emergency Medicine'), ('ANESTHESIOLOGY', 'Anesthesiology'), ('PSYCHIATRY', 'Psychiatry'), ('INTERNAL_MEDICINE', 'Internal Medicine'), ('FAMILY_MEDICINE', 'Family Medicine'), ('PUBLIC_HEALTH', 'Public Health')], max_length=100)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('contact_information', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('doctors', models.ManyToManyField(related_name='departments', to=settings.AUTH_USER_MODEL)),
                ('head_of_department', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_headed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
